### ISSUE TITLE
When is Turret.send_result used ?

### ISSUE THREAD

**Issue by ZuluPro** [TheGhouls/oct-turrets#12]
I wrote a custom turret and overrided `Turret.send_result used`.
Unfortunately I can't figure out when it is used. It is supposed here: https://github.com/TheGhouls/oct-turrets/blob/master/oct_turrets/turret.py#L112

In HQ side, result are compiled, etc...

**Comment by karec** [comment]
`Turret.send_result` is not used anymore. I didn't had time to refactor turrets at the moment so this method still exists.

In previous versions it was used to send results back to HQ, but it created a bottleneck, turret wasn't able to send back all received messages from canons to HQ.

**Comment by ZuluPro** [comment]
So where does the action is made ?
Or does the new result collector will be here soon ?

**Comment by karec** [comment]
Result collector still in HQ. Main difference is that now cannons send results directly to HQ at the moment

**Comment by ZuluPro** [comment]
Do you think [these patch](https://github.com/TheGhouls/oct/compare/3e24151be29a4d20048903082f47be44eea92959?expand=1) will be included soon ?

**Comment by karec** [comment]
Unfortunately I don't have many time to work in this patch at the moment and since I'm alone on this project it may take some times before release.

But all these changes are avaible on v1 branch of OCT and passe tests, so if you really want them you can use the branch instead of pypi package
